install ack
install freetds
install git
install openssl
install tmux
install tree 
install wget
install chruby
install ruby-install
install docker
install docker-machine
install docker-compose
install reattach-to-user-namespace
install heroku
