install ack
install freetds
install git
install openssl
install tmux
install tree 
install wget
install chruby
install ruby-install
install reattach-to-user-namespace
install vim
install cheat
install bat